# Generated by Django 5.1.6 on 2025-03-21 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='stock',
            new_name='quantity',
        ),
    ]
